version: "3.10"

services:
  api:
    build: .
    container_name: event_manager_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
